FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /mock-dynamo ./cmd/mock-dynamo

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /mock-dynamo /usr/local/bin/mock-dynamo
EXPOSE 9090
ENTRYPOINT ["mock-dynamo"]
